### ISSUE TITLE
Problems with / commands.

### ISSUE THREAD

**Issue by GustavRaispits** [xNul/chat-llama-discord-bot#1]
I've recently set up ooba text-generation-webui with 4bit patch and the site works correctly, I'm using llama-13b-hf. I'm trying to run bot.py using miniconda through the textgen env with python 3.10.10, what are the required modules for making chat-llama-discord-bot work correctly? I didn't find any requirements.txt file for installing every module.
![myz9YWh](https://user-images.githubusercontent.com/34628862/227044343-3e06b7e1-00bd-4352-b8ae-3e40ca66e098.png)
It says that the slash command is not valid, looks like that some / commands "disappears" when using the /reset or /index reset commands.

That's what happens when I try to use /reply without using the /reset command for making the initial prompt:

![2Pg8ppq](https://user-images.githubusercontent.com/34628862/227044808-0cd4139b-3e85-4dd0-b29f-bda794cd661c.png)

Sometimes the CMD doesn't even output errors when the / commands "crashes"

![02nS8wp](https://user-images.githubusercontent.com/34628862/227044680-ad725486-3dd3-4be3-948e-723d8a0dc9b1.png)

I believe that this repo got great potential, hoping to get a response!

**Comment by xNul** [comment]
I think the problem in the first screenshot was happening because the commands from your bot hadn't registered with Discord yet. It takes a few minutes before they will work with a new bot.

For the second problem, it looks like text-generation-webui updated again. It updates every few days with breaking changes to both the install instructions and the internal API I'm leveraging because of how much development there is going on with LLaMA atm.

**Comment by xNul** [comment]
I've applied a fix for the text-generation-webui breaking changes in this commit https://github.com/xNul/chat-llama-discord-bot/commit/a14deeff25fc521b14f50e918486e7d7e0387936. Thanks for reporting the issue and hope you enjoy the bot!
